{
 "title": "Mantis",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(jvm_classes_loaded, instance)"
   },
   {
    "name": "akka_node",
    "label": "akka_node",
    "query": "label_values(akka_system_active_actors_count,instance)"
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "percentile", "label": "percentile", "query": "0.5,0.90,0.95,0.99,0.999" },
   {
    "name": "system",
    "query": "label_values(akka_system_unhandled_messages_total, system)"
   }
  ]
 },
 "panels": [
  {
   "title": "Regular Synchronization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Import time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "rate(app_regularsync_blocks_propagation_timer_seconds_sum[$__rate_interval]) / rate(app_regularsync_blocks_propagation_timer_seconds_count[$__rate_interval])",
       "legendFormat": "{{blocktype}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Fast Synchronization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "FastSync Total Time in Minutes",
     "type": "stat",
     "description": "Total time taken for FastSync to complete",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "app_fastsync_totaltime_minutes_gauge",
       "legendFormat": "minutes"
      }
     ]
    },
    {
     "title": "Pivot Block",
     "type": "stat",
     "description": "Current Pivot Block",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "app_fastsync_block_pivotBlock_number_gauge"
      }
     ]
    },
    {
     "title": "Best Header",
     "type": "stat",
     "description": "Current Best Header",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "app_fastsync_block_bestFullBlock_number_gauge"
      }
     ]
    },
    {
     "title": "Best Full Block",
     "type": "stat",
     "description": "Current Best Full Block",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "app_fastsync_block_bestFullBlock_number_gauge"
      }
     ]
    },
    {
     "title": "MPT Nodes Download time",
     "type": "graph",
     "description": "Time is takes to download each batch of MPT Nodes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(app_fastsync_state_downloadState_timer_seconds_sum[$__interval]) / rate(app_fastsync_state_downloadState_timer_seconds_count[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MPT Total Nodes",
     "type": "graph",
     "description": "Number of MPT Nodes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "app_fastsync_state_totalNodes_gauge",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MPT Downloaded Nodes",
     "type": "graph",
     "description": "Number of MPT Downloaded Nodes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "app_fastsync_state_downloadedNodes_gauge",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Block Headers Download time",
     "type": "graph",
     "description": "Time is takes to download each batch of Block Headers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short", "label": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(app_fastsync_block_downloadBlockHeaders_timer_seconds_sum[$__interval]) / rate(app_fastsync_block_downloadBlockHeaders_timer_seconds_count[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Block Bodies Download time",
     "type": "graph",
     "description": "Time is takes to download each batch of Block Bodies",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short", "label": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(app_fastsync_block_downloadBlockBodies_timer_seconds_sum[$__interval]) / rate(app_fastsync_block_downloadBlockBodies_timer_seconds_count[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Block Receipts Download time",
     "type": "graph",
     "description": "Time is takes to download each batch of Block Receipts",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short", "label": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(app_fastsync_block_downloadBlockReceipts_timer_seconds_sum[$__interval]) / rate(app_fastsync_block_downloadBlockReceipts_timer_seconds_count[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Blockchain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block number / Time",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none", "label": "Block number" }
     ],
     "targets": [
      { "expr": "app_sync_block_number_gauge", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Transactions in pool / Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "none", "label": "# of transactions" }
     ],
     "targets": [
      {
       "expr": "app_transactions_pool_size_gauge",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transactions in block / Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "none", "label": "# of transactions" }
     ],
     "targets": [
      {
       "expr": "app_sync_block_transactions_gauge_gauge",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Ommers in block / Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "none", "label": "# of transactions" }
     ],
     "targets": [
      { "expr": "app_sync_block_uncles_gauge", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Gas limit / Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "none", "label": "gas limit" }
     ],
     "targets": [
      { "expr": "app_sync_block_gasLimit_gauge", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Block time / Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s", "label": "block time" }
     ],
     "targets": [
      {
       "expr": "app_sync_block_timeBetweenParent_seconds_gauge_gauge",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Gas used / Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "none", "label": "gas used" }
     ],
     "targets": [
      { "expr": "app_sync_block_gasUsed_gauge", "legendFormat": "{{instance}}" }
     ]
    }
   ]
  },
  {
   "title": "JSON RPC endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(app_json_rpc_methods_timer_seconds_sum[$__rate_interval])/rate(app_json_rpc_methods_timer_seconds_count[$__rate_interval])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Maximum duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "app_json_rpc_methods_timer_seconds_max"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "generateBlock - average duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(app_consensus_blocks_generate_timer_seconds_sum[$__rate_interval])/rate(app_consensus_blocks_generate_timer_seconds_count[$__rate_interval])",
       "legendFormat": "{{class}}"
      }
     ]
    },
    {
     "title": "generateBlock - maximum duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "app_consensus_blocks_generate_timer_seconds_max",
       "legendFormat": "{{class}}"
      }
     ]
    },
    {
     "title": "Mined block evaluation - average duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "rate(app_consensus_minedblocks_evaluation_timer_seconds_sum[$__rate_interval]) / rate(app_consensus_minedblocks_evaluation_timer_seconds_count[$__rate_interval])\n"
      }
     ]
    }
   ]
  },
  {
   "title": "OBFT Federation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Stable Checkpoint in Ledger",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "morpho_checkpoint_stable_state_pow_block_number",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Number of Votes for Latest Checkpoint",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "Nb Votes" }
     ],
     "targets": [
      {
       "expr": "morpho_checkpoint_nb_votes_latest",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Block Number Pushed to Mantis",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Midnight Block Number" }
     ],
     "targets": [
      {
       "expr": "morpho_checkpoint_pushed_pow_block_number",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Checkpoint in the Stable Ledger",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "Midnight Block Number" }
     ],
     "targets": [
      {
       "expr": "morpho_checkpoint_stable_state_pow_block_number",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Checkpoint in the Unstable Ledger",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Midnight Block Number" }
     ],
     "targets": [
      {
       "expr": "morpho_checkpoint_unstable_state_pow_block_number",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Latest Checkpoint Candidate fetched from Mantis",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Midnight Block Number" }
     ],
     "targets": [
      {
       "expr": "morpho_midnight_latest_pow_block_number",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "apdex_network_healthy $node",
     "type": "singlestat",
     "description": "Apdex given:\n- satisfied count = sent + received - low - high\n- tolerant count = low\n- total count = sent + received\n",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "(sum(increase(app_network_messages_received_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_network_messages_sent_counter_total{instance=\"$node\"}[$__range])) - sum(increase(app_network_peers_highSeverityOffense_counter_total{instance=\"$node\"}[$__range])) - sum(increase(app_network_peers_lowSeverityOffense_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_network_peers_lowSeverityOffense_counter_total{instance=\"$node\"}[$__range])) / 2) / (sum(increase(app_network_messages_received_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_network_messages_sent_counter_total{instance=\"$node\"}[$__range])))"
      }
     ]
    },
    {
     "title": "Blacklisted peers $node",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "app_network_peers_blacklisted_gauge{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "Discovered peers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "number of peers" }
     ],
     "targets": [
      {
       "expr": "app_network_discovery_foundPeers_gauge",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Ratio of tried / discovered peers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit", "label": "%" }
     ],
     "targets": [
      { "expr": "app_network_tried_peers_gauge", "legendFormat": "nb_tried_peers" },
      {
       "expr": "app_network_discovery_foundPeers_gauge",
       "legendFormat": "nb_discovered_peers"
      }
     ]
    },
    {
     "title": "Incoming total peers",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "number of peers" }
     ],
     "targets": [
      {
       "expr": "app_network_peers_pending_gauge",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Incoming handshaked peers",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "number of peers" }
     ],
     "targets": [
      {
       "expr": "app_network_peers_incoming_handshaked_gauge",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Incoming pending peers",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "number of peers" }
     ],
     "targets": [
      {
       "expr": "app_network_peers_incoming_total_gauge - app_network_peers_incoming_handshaked_gauge",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Outgoing total peers",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "number of peers" }
     ],
     "targets": [
      {
       "expr": "app_network_peers_outgoing_handshaked_gauge",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Outgoing handshaked peers",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "number of peers" }
     ],
     "targets": [
      {
       "expr": "app_network_peers_outgoing_handshaked_gauge",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Outgoing pending peers",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "number of peers" }
     ],
     "targets": [
      {
       "expr": "app_network_peers_outgoing_total_gauge - app_network_peers_outgoing_handshaked_gauge",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Messages sent",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "none", "label": "number of messages" }
     ],
     "targets": [
      {
       "expr": "increase(app_network_messages_sent_counter_total[$__range])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Messages received",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "none", "label": "number of messages" }
     ],
     "targets": [
      {
       "expr": "increase(app_network_messages_received_counter_total[$__range])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PoW",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOHK mined blocks",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(app_sync_block_minedBlocks_counter_total[$__range]))"
      }
     ]
    },
    {
     "title": "Mined blocks (not all mined blocks end up included in the chain)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 8 },
     "yaxes": [
      { "format": "none", "label": "number of blocks" }
     ],
     "targets": [
      {
       "expr": "increase(app_sync_block_minedBlocks_counter_total[$__range])    ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Mined blocks rate ($node)",
     "type": "singlestat",
     "description": "mined blocks / total blocks in the chain * 100",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(app_sync_block_minedBlocks_counter_total{instance=\"$node\"}[$__range]))) / (sum(increase(app_sync_block_minedBlocks_counter_total[$__range]))) * 100"
      }
     ]
    },
    {
     "title": "Is Mining?",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {}
     ]
    },
    {
     "title": "Hashrate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "none", "label": "hashes/s" }
     ],
     "targets": [
      { "expr": "midnight_node_miner_hashrate", "legendFormat": "{{alias}}" }
     ]
    }
   ]
  },
  {
   "title": "$node | General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Start time $node",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_start_time_seconds{instance=\"$node\"}*1000"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 6, "y": 8 },
     "format": "dateTimeFromNow",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_start_time_seconds{instance=\"$node\"}*1000"
      }
     ]
    },
    {
     "title": "Latest block number",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 11, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "app_sync_block_number_gauge{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "AVG Block time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
     "format": "s",
     "valueName": "avg",
     "targets": [
      {
       "expr": "app_sync_block_timeBetweenParent_seconds_gauge{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "Latest block time",
     "type": "singlestat",
     "description": "Time between latest imported block and its parent",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "app_sync_block_timeBetweenParent_seconds_gauge{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "Latest checkpoint block number",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 11, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(app_sync_block_checkpoint_number_gauge{instance=\"$node\"})"
      }
     ]
    },
    {
     "title": "Log Events",
     "type": "graph",
     "gridPos": { "h": 5, "w": 16, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "increase(logback_appender_total_counter{instance=\"$node\"}[1m])",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "apdex_RPC responses",
     "type": "singlestat",
     "description": "- Apdex RPC_responses = (SatisfiedCount + ToleratingCount / 2) / TotalSamples\n\nSatisfiedCount = MethodsSuccessCounter\nToleratingCount = MethodsErrorCounter\nTotalSamples = MethodsSuccessCounter + MethodsErrorCounter + MethodsExceptionCounter",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(app_json_rpc_methods_success_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_json_rpc_methods_error_counter_total{instance=\"$node\"}[$__range])) / 2) / (sum(increase(app_json_rpc_methods_success_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_json_rpc_methods_error_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_json_rpc_methods_exception_counter_total{instance=\"$node\"}[$__range])))",
       "legendFormat": "apdex_rpc_responses"
      }
     ]
    },
    {
     "title": "rpc_error_responses",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 12 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(app_json_rpc_methods_error_counter_total{instance=\"$node\"}[$__range])) / (sum(increase(app_json_rpc_methods_success_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_json_rpc_methods_error_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_json_rpc_methods_exception_counter_total{instance=\"$node\"}[$__range])))) * 100",
       "legendFormat": "rpc_error_responses"
      }
     ]
    },
    {
     "title": "rpc_fatal_errors_responses",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 14 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(app_json_rpc_methods_exception_counter_total{instance=\"$node\"}[$__range])) / (sum(increase(app_json_rpc_methods_success_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_json_rpc_methods_error_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_json_rpc_methods_exception_counter_total{instance=\"$node\"}[$__range])))) * 100",
       "legendFormat": "rpc_fatal_errors_responses"
      }
     ]
    }
   ]
  },
  {
   "title": "$node | JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Pool Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{instance=~\"$node\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_state{instance=\"$node\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Threads used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_current{instance=\"$node\"}",
       "legendFormat": "current"
      },
      {
       "expr": "jvm_threads_daemon{instance=\"$node\"}",
       "legendFormat": "daemon"
      }
     ]
    },
    {
     "title": "Memory used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{instance=\"$node\"}",
       "legendFormat": "{{area}} memory"
      }
     ]
    },
    {
     "title": "Class loading",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "GC count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_collection_seconds_count{instance=\"$node\"}",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "GC time / 1 min. rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"$node\"}[1m])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{instance=\"$node\"}",
       "legendFormat": "open"
      },
      {
       "expr": "process_max_fds{instance=\"$node\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Akka System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unhandled Messages",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": " sum(rate(akka_system_unhandled_messages_total{instance=~\"$akka_node\", system=~\"$system\"}[$interval])) by (system)"
      }
     ]
    },
    {
     "title": "Dead Letters",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(akka_system_dead_letters_total{instance=~\"$akka_node\", system=~\"$system\"}[$interval])) by (system)"
      }
     ]
    },
    {
     "type": "table-old",
     "gridPos": { "h": 5, "w": 6, "x": 8, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(akka_system_active_actors_count{instance=\"$akka_node\", system=\"$system\"}[$interval])) by (system)",
       "legendFormat": "Active Actors"
      },
      {
       "expr": "sum(irate(akka_system_processed_messages_total{instance=\"$akka_node\",tracked=\"true\", system=\"$system\"}[$interval])) by (system)",
       "legendFormat": "Processed Messages (tracked=true)"
      },
      {
       "expr": "sum(irate(akka_system_processed_messages_total{instance=\"$akka_node\",tracked=\"false\", system=\"$system\"}[$interval])) by (system)",
       "legendFormat": "Processed Messages (tracked=false)"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 14, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "akka_group_errors_total", "legendFormat": "{{group}}" }
     ]
    }
   ]
  },
  {
   "title": "Akka Group Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processing Time ($percentile)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum(rate(akka_group_processing_time_seconds_bucket{instance=~\"$akka_node\"}[$interval])) by (le, group)) * 1000",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "Time in Mailbox ($percentile)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum(rate(akka_group_time_in_mailbox_seconds_bucket{instance=~\"$akka_node\"}[$interval])) by (le, group))",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "Mailbox Size / Number of Members",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(akka_group_mailbox_size_sum{instance=~\"$akka_node\"}[$interval]) / rate(akka_group_mailbox_size_count{instance=~\"$akka_node\"}[$interval])",
       "legendFormat": "{{group}} mailbox"
      },
      {
       "expr": "rate(akka_group_members_sum{instance=~\"$akka_node\"}[$interval]) / rate(akka_group_members_count{instance=~\"$akka_node\"}[$interval])",
       "legendFormat": "members of {{group}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Executor Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number Of Threads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(executor_threads_total_count{instance=~\"$akka_node\"}[$interval]) / rate(executor_threads_total_sum{instance=~\"$akka_node\"}[$interval])",
       "legendFormat": "System:{{akka_system}} - Name: {{name}} - Type: {{type}}"
      }
     ]
    },
    {
     "title": "Number Of Tasks Completed",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(executor_tasks_completed_total{instance=~\"$akka_node\"}[$interval])",
       "legendFormat": "{{ instance }}: {{ name }} ({{ type }}) {{akka_system}}"
      }
     ]
    },
    {
     "title": "Queue Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(executor_queue_size_bucket{instance=~\"$akka_node\", le=\"+Inf\"}[$interval])",
       "legendFormat": "{{ akka_system }}: {{ name }} ({{ type }})"
      }
     ]
    },
    {
     "title": "Maximum Number of Threads",
     "type": "graph",
     "description": "Tracks executor maximum number of Threads",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "executor_threads_max{instance=~\"$akka_node\"}",
       "legendFormat": "System: {{akka_system}} - Name: {{name}} - Type: {{type}}"
      }
     ]
    },
    {
     "title": "Minimum Number of Threads",
     "type": "graph",
     "description": "Tracks executor minimum number of Threads",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "executor_threads_min{instance=~\"$akka_node\"}",
       "legendFormat": "System: {{akka_system}} - Name: {{name}} - Type: {{type}}"
      }
     ]
    },
    {
     "title": "Executor parallelism",
     "type": "graph",
     "description": "Tracks executor parallelism",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "executor_parallelism{instance=~\"$akka_node\"}",
       "legendFormat": "System: {{akka_system}} - Name: {{name}} - Type: {{type}}"
      }
     ]
    }
   ]
  }
 ]
}