steps:
  - label: ":nix::point_right::pipeline:"
    command: |
      export NIX_PATH="nixpkgs=$(nix-instantiate --eval --strict --json --read-write-mode -E '(import nix/sources.nix).nixpkgs' | tr -d '"')"
      nix-instantiate --eval --strict --json --expr '(import ./.buildkite { pipeline = ./.buildkite/pipeline.nix; })' \
      | buildkite-agent pipeline upload --no-interpolation
    agents:
      queue: project42
    timeout_in_minutes: 60
