steps:
  - label: ":nix::point_right::pipeline:"
    command: |
      export NIX_PATH="nixpkgs=$(nix-instantiate --eval --strict --json --read-write-mode -E '(import nix/sources.nix).nixpkgs' | tr -d '"')"
      nix-instantiate --eval --strict --json --expr '(import ./.buildkite { pipeline = ./.buildkite/pipeline.nix; })' \
      | buildkite-agent pipeline upload --no-interpolation
    agents:
      queue: project42
    timeout_in_minutes: 60
#  - label: "Mantis Automation"
#    command:
#    - "curl https://raw.githubusercontent.com/input-output-hk/mantis-automation/main/.buildkite/pipeline_erc20_pr.yml -o automation.yml"
#    - "buildkite-agent pipeline upload automation.yml"
