FROM ubuntu:xenial

# This "dev" image creates enough of a Mantis build environment,
# so that the actual Mantis images can be built in less time.
# We are particularly interested in caching the dependencies needed
# during the build process. This means that whenever those change,
# the "dev" image must be recreated.

# See the accompanying `build-dev.sh` script for tagging details.

ENV DEBIAN_FRONTEND noninteractive

ARG SBT_VERIFY_TAG
ENV SBT_VERIFY_TAG ${SBT_VERIFY_TAG:-v0.4.1}

ARG MANTIS_TAG
ENV MANTIS_TAG ${MANTIS_TAG:-phase/iele_testnet}

# Just install enough to get nix up and running
RUN apt-get update \
    && apt-get dist-upgrade -y \
    && apt-get install -y curl bzip2 locales \
    && locale-gen en_US.UTF-8 \
    && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 \
    && adduser --disabled-password --gecos '' mantis \
    && mkdir /nix \
    && chown mantis:mantis /nix \
    && su mantis -c 'curl https://nixos.org/nix/install | sh && . ~/.nix-profile/etc/profile.d/nix.sh && nix-channel --update && tail -n 1 ~/.profile >> ~/.bashrc' \
    && ln -s /home/mantis/mantis-dist/app /app \
    && apt-get purge -y curl bzip2 \
    && apt-get clean -y \
    && rm -rf /var/cache/debconf/* /var/lib/apt/lists/* /var/log/* /tmp/* /var/tmp/*

USER mantis
WORKDIR /home/mantis
ENV USER mantis

# install java, sbt, git, unzip
RUN . ~/.nix-profile/etc/profile.d/nix.sh \
    && nix-env -i openjdk-8u172b11 sbt-1.1.4 git unzip \
    && nix-collect-garbage

# TODO: Could just use a nix-shell and garbage collect (e.g. git, unzip, sbt) after the installations ...
RUN . ~/.nix-profile/etc/profile.d/nix.sh \
    && mkdir repos && cd repos \
    && git clone https://github.com/input-output-hk/sbt-verify.git \
    && cd sbt-verify \
    && git checkout $SBT_VERIFY_TAG \
    && sbt publishLocal \
    && cd - \
    && git clone https://github.com/input-output-hk/mantis.git \
    && cd mantis \
    && git checkout $MANTIS_TAG \
    && git submodule update --init \
    && sbt 'set test in Test := {}' dist \
    && cd ~ \
    && rm -rf ~/repos/*
