# This file was automatically generated by Sbtix. Do not edit manually.
{
  "versioning" = [{
      "scalaVersion" = "2.13.4";
      "sbtVersion" = "1.3.6";
    }];
  "repos" = {
    "nix-public" = "";
    "nix-sbt-plugin-releases" = "[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]";
  };
  "artifacts" = {
  };
}
