{
 "title": "Besu overview",
 "description": "Provides an overview of Besu nodes",
 "tags": [
  "besu",
  "ethereum"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "system",
    "label": "System",
    "query": "query_result(ethereum_blockchain_height or besu_blockchain_height)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overview",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (instance) (besu_blockchain_height{instance=~\"$system\"} or ethereum_blockchain_height{instance=~\"$system\"})",
     "legendFormat": "Chain Height"
    },
    {
     "expr": "sum by (instance) (besu_synchronizer_best_known_block{instance=~\"$system\"} or ethereum_best_known_block_number{instance=~\"$system\"})"
    },
    {
     "expr": "sum by (instance) ((besu_synchronizer_best_known_block{instance=~\"$system\"} - besu_blockchain_height{instance=~\"$system\"}) or (ethereum_best_known_block_number{instance=~\"$system\"} - ethereum_blockchain_height{instance=~\"$system\"}))"
    },
    {
     "expr": "sum by (instance) (besu_blockchain_difficulty_total{instance=~\"$system\"})",
     "legendFormat": "Total Difficulty"
    },
    {
     "expr": "sum by (instance) ((1/rate(besu_blockchain_height{instance=~\"$system\"}[5m])) or (1/rate(ethereum_blockchain_height{instance=~\"$system\"}[5m])))"
    },
    {
     "expr": "sum by (instance) (time() - besu_blockchain_chain_head_timestamp{instance=~\"$system\"})"
    },
    {
     "expr": "sum by (instance) (besu_peers_peer_count_current{instance=~\"$system\"} or ethereum_peer_count{instance=~\"$system\"})",
     "legendFormat": "Peer Count"
    },
    {
     "expr": "sum by (instance) ((besu_peers_peer_count_current{instance=~\"$system\"} / besu_network_peers_limit{instance=~\"$system\"}) or ethereum_peer_count{instance=~\"$system\"} / ethereum_peer_limit{instance=~\"$system\"})"
    }
   ]
  },
  {
   "title": "Fast Sync Progress",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (instance) ((besu_blockchain_height{instance=~\"$system\"} or ethereum_blockchain_height{instance=~\"$system\"}) and besu_synchronizer_world_state_pending_requests_current{instance=~\"$system\"} > 0)",
     "legendFormat": "Chain Height"
    },
    {
     "expr": "sum by (instance) (besu_synchronizer_fast_sync_pivot_block_current{instance=~\"$system\"} and besu_synchronizer_world_state_pending_requests_current{instance=~\"$system\"} > 0)"
    },
    {
     "expr": "sum by (instance) (besu_synchronizer_fast_sync_pivot_block_current{instance=~\"$system\"} - besu_blockchain_height{instance=~\"$system\"} and besu_synchronizer_world_state_pending_requests_current{instance=~\"$system\"} > 0)"
    },
    {
     "expr": "sum by (instance) (besu_synchronizer_world_state_pending_requests_current{instance=~\"$system\"} > 0)"
    },
    {
     "expr": "sum by (instance) (besu_synchronizer_world_state_completed_requests_total{instance=~\"$system\"} and besu_synchronizer_world_state_pending_requests_current{instance=~\"$system\"} > 0)"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "1/rate(besu_blockchain_height{instance=~\"$system\"}[5m]) or 1/rate(ethereum_blockchain_height{instance=~\"$system\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blocks Behind",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "besu_synchronizer_best_known_block{instance=~\"$system\"} - besu_blockchain_height{instance=~\"$system\"} or ethereum_best_known_block_number{instance=~\"$system\"} - ethereum_blockchain_height{instance=~\"$system\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Memory Pool Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_memory_pool_bytes_used", "legendFormat": "{{pool}}" }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_state", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "current" },
    { "expr": "jvm_threads_daemon", "legendFormat": "deamon" }
   ]
  },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_memory_bytes_used", "legendFormat": "{{area}} memory" }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_classes_loaded", "legendFormat": "loaded" }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC time / 5 min. rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum[5m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Peers connected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "besu_peers_connected_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Disconnected peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "besu_peers_disconnected_total", "legendFormat": "{{disconnectReason}}" }
   ]
  },
  {
   "title": "Peers pending request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "besu_peers_pending_peer_requests_current",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(besu_network_discovery_messages_outbound[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Messages Inbound",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(besu_network_discovery_messages_inbound[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}