#!/usr/bin/env sh

dir="$(cd "$(dirname "$0")" && pwd)"

separator="--"
if [[ $@ =~ "--" ]]; then
  separator=""
fi

retesteth $@ $separator --testpath $dir/tests --datadir $dir/config --clients mantis
